### ISSUE TITLE
Wrong packages for Google

### ISSUE THREAD

**Issue by robertmylne** [SolidStateGroup/react-native-firebase-auth#10]
I am getting this error:
```npm WARN react-native-firebase-auth@0.0.11 requires a peer of react-native-google-signin@>=0.8.0 but none was installed.```

But your docs have a completely different package listed as the dependency.
`react-native-google-signin` vs `react-native-google-sign-in`

So is it this package `https://github.com/joonhocho/react-native-google-sign-in#getting-started` or this package needed `https://github.com/devfd/react-native-google-signin`?

**Comment by lukefanning** [comment]
We recently switched over to `https://github.com/joonhocho/react-native-google-sign-in` but we hadn't published a new version of this module. I have now just done so, please install v1.0.0.
