### ISSUE TITLE
How do I increase permissions on facebookLogin?

### ISSUE THREAD

**Issue by mareebsiddiqui** [SolidStateGroup/react-native-firebase-auth#11]
Ive implemented my facebook login but when i see my firebase it just shows email and if email is verified i want more of the user's data how do I do that? Like friends and news feed and stuff?

**Comment by kyle-ssg** [comment]
https://github.com/SolidStateGroup/react-native-firebase-auth/blob/master/index.js#L86
You can supply permissions here, it defaults to ['email'] - this behaviour is defined here:

https://github.com/SolidStateGroup/react-native-firebase-auth/blob/master/auth.js#L5

**Comment by mareebsiddiqui** [comment]
I changed my code to this:
`FireAuth.facebookLogin(["user_friends", 'email', 'public_profile']);`

But when i reload my app in the emulator it does not ask for permission it says you have already authorize your app. It means its not picking up these permissions?

**Comment by kyle-ssg** [comment]
Apologies for late reply, you need to logout of facebook for these changes to take place. If you still see an issue after this I'd suggest putting a breakpoint on the relevant line in react-native-facebook-login, this package definitely passes on the permissions you provide.
