### ISSUE TITLE
Phone Auth

### ISSUE THREAD

**Issue by perrosnk** [SolidStateGroup/react-native-firebase-auth#13]
Any plans to support Phone Auth that is going to replace Twitter Digits?

**Comment by cpsiaki** [comment]
+1

**Comment by jariwalabhavesh** [comment]
+1

**Comment by mareebsiddiqui** [comment]
+1

**Comment by dabeeeenster** [comment]
We're happy to take pull requests on this - we dont have time to work on it right now!

**Comment by kyle-ssg** [comment]
No immediate plans to implement this (unless someone kindly provides a PR), best bet is to have a look at this:
https://github.com/invertase/react-native-firebase/issues/119
