### ISSUE TITLE
¿how can use callback in FB or GG login?

### ISSUE THREAD

**Issue by Brhernann** [SolidStateGroup/react-native-firebase-auth#16]
i can`t use the callback .then:

`facebookLogin() {
  FireAuth.facebookLogin()
  .then((res) => {
console.log(res)
)
}`

`googleLogin() {
  FireAuth.googleLogin()
  .then((res) => {
console.log(res)
)
}`

How can know if the user is logged?

**Comment by kyle-ssg** [comment]
```  FireAuth.setup(this.onLogin, this.onUserChange, this.onLogout, this.emailVerified, this.onError);``` first arg is an onLogin callback
