### ISSUE TITLE
Module does not exist in the module map

### ISSUE THREAD

**Issue by dcalixto** [SolidStateGroup/react-native-firebase-auth#18]
Someone with this issue?
react-native: 0.49.3

UnableToResolveError: Unable to resolve module `react-native-facebook-login` from `/Users/dcalix/booty/node_modules/react-native-firebase-auth/auth.js`: Module does not exist in the module map

**Comment by kyle-ssg** [comment]
https://github.com/SolidStateGroup/react-native-firebase-auth#project-setup

You need to install react-native-facebook-login as a dependency
