### ISSUE TITLE
What does "in the usual way" mean?

### ISSUE THREAD

**Issue by yofu1234** [SolidStateGroup/react-native-firebase-auth#2]
On the readme it says:

> You will need setup both of the social platform dependencies in the usual way.

https://github.com/devfd/react-native-google-signin#project-setup-and-initialization https://github.com/magus/react-native-facebook-login#setup

What does "the usual way" mean?

**Comment by lukefanning** [comment]
Hi I have slightly reworded that line to make it more obvious that you need to fully setup the two React Native modules that are linked just below it.

**Comment by yofu1234** [comment]
Thank you 👍
