### ISSUE TITLE
Will this work with https://github.com/facebook/react-native-fbsdk?

### ISSUE THREAD

**Issue by jrmcdona** [SolidStateGroup/react-native-firebase-auth#3]
I have fbsdk already working, just wondering if this will work with that.   Will look into it but didn't want to spend much time if somebody already has tried.

Thanks

**Comment by kyle-ssg** [comment]
Hey jrmcdona, this repository uses ```react-native-facebook-login``` and ```react-native-google-signin``` as peer dependencies intended for social auth. https://github.com/SolidStateGroup/react-native-firebase-auth/blob/master/auth.js wraps all the social auths together and is used internally by fireauth.

Having said that you could just auth with firebase directly and fireauth would automatically pick up the onLogin event, we've done this in the past with custom auth strategies:
```
 customFacebookLogin(permissions)
      .then((token) => (
        firebase.auth()
          .signInWithCredential(firebase.auth.FacebookAuthProvider.credential(token))
      ))
```
You could then use fireauth as per usual.

**Comment by kyle-ssg** [comment]
Closing for now, feel free to reopen if you have any more questions regarding this.
