### ISSUE TITLE
Delay between login activity and main screen using facebook login

### ISSUE THREAD

**Issue by njs2017** [SolidStateGroup/react-native-firebase-auth#4]
Hello, 
when I am openning the app and already logged in with facebook before, I spend 3-4 seconds on the login page.. is there any method I could use to see that auth is being initialized and display some loading icon?

**Comment by kyle-ssg** [comment]
Hey @njs2017, have you checked when you're initialising fireauth ? Technically all that's going on behind the scenes is a call to ```firebase.auth().onAuthStateChanged```, internally this always calls back pretty much immediately regardless of if they login successfully and if they are online.

I'd suggest putting a breakpoint inside <a href="https://github.com/SolidStateGroup/react-native-firebase-auth/blob/master/index.js#L17">here</a> to see if there is really that much of a delay between ```firebase.auth().onAuthStateChanged``` and ```if(user)```.

In terms of setting a loading state I'd suggest the following:

- default to loading as being true before you call fireauth.setup
- set loading to false on onLogin, onLogout, onError (https://github.com/SolidStateGroup/react-native-firebase-auth/blob/master/index.js#L26)

I may implement an onLoadingChanged callback in a future version however this might encourage people to set state too many times.

**Comment by kyle-ssg** [comment]
Feel free to reopen this if this if it comes up again.
