### ISSUE TITLE
Firebase auth only for Facebook

### ISSUE THREAD

**Issue by amirc** [SolidStateGroup/react-native-firebase-auth#5]
Hi,
Is there an option to use react-native-firebase-auth without react-native-google-signin ?
When I try to use it only with react-native-facebook-login I get an exception.
I just need Facebook authentication in my app.

Thanks,
Amir.

**Comment by leyuan** [comment]
Hey @amirc 

I have the same needs. I was scratching my head trying to find a way not implementing Google but using this. But instead I just read the source code, and picked the parts that I need. There are only two files, and very well written. Let me know if you still can't figure a way to do it.

And..Thanks for the author providing this sincerely!

**Comment by amirc** [comment]
Cool thanks, sounds like a good idea. And of course, thanks for the author!

**Comment by kyle-ssg** [comment]
Yep, internally we use this project for quite a few projects. In the cases where we only use one of Facebook/Google  just keep default facebook/google app ids.

Also, Cheers @leyuan we try our best 😄
