### ISSUE TITLE
What is IOS_CLIENT_ID and where/how do I obtain it???

### ISSUE THREAD

**Issue by sheprdinc** [SolidStateGroup/react-native-firebase-auth#6]
Is it the same thing as the FacebookAppID??? And if the same, it should be a string, not a number, correct?

If not the same, where/how do I obtain an IOS_CLIENT_ID???

Also, if it's an 'IOS_CLIENT_ID', then why does the comment right next to it claim that it's a 'Google Sign in options'???

FireAuth.init({iosClientId: <IOS_CLIENT_ID>}); // Google Sign in options. You will need iosClientId for iOS apps.

**Comment by kyle-ssg** [comment]
Hey there, apologies for the mixup. This is the CLIENT_ID found in your GoogleService-Info.plist. 

**Edit** I've updated the readme to help clear things up, thanks for reporting this.
