### ISSUE TITLE
Don't you need to init your firebase?

### ISSUE THREAD

**Issue by heherbertzhang** [SolidStateGroup/react-native-firebase-auth#7]
It's not showing in the example that you init the firebase itself.

Also are you sure the firebase.auth() will always return the same variable?  Why don't you store it in a global variable fireauth so that later on users can use the fireauth.storage.ref() etc?

**Comment by lukefanning** [comment]
Hi there, yes you would need to initialise firebase within your project before initialising this module. firebase.auth() will always return the same variable as firebase is imported as a singleton.
