### ISSUE TITLE
On register, pushes an object to firebase

### ISSUE THREAD

**Issue by stevenconner** [SolidStateGroup/react-native-firebase-auth#9]
when registering a user, the library (either yours or the ones that it implements to make the login work for social platforms) is pushing an object onto the firebase database under 'profiles'.  I'm pushing an object of my own to track the user the way i'd like to on the database, so I was trying to figure out where to either edit this functionality or disable it entirely and use my own implementation, but I can't seem to figure out where the library is making that happen. Any guidance would be greatly appreciated!

**Comment by lukefanning** [comment]
Sorry about the late response. That would be our library that's doing that. If you look in `index.js` in `setup() --> firebase.auth().onAuthStateChanged()` you will see that it creates a database ref to `profiles/<user-id>` which it updates with the latest emailVerified and email values. We welcome pull requests! Just make sure that original behaviour is left intact by default.
